### ISSUE TITLE
Bug: Menu with Toggle Element won't always open

### ISSUE THREAD

**Issue by calvinrbnspiess** [NickDJM/accessible-menu#109]
## Summary

We're using accessible-menu for the site of a local authority. I experienced an issue when having a fixed navigation and a DisclosureMenu looking like this:

<img width="786" alt="Bildschirmfoto 2021-06-01 um 10 51 15" src="https://user-images.githubusercontent.com/5459550/120295432-698c1280-c2c7-11eb-96b3-67bda8071199.png">

During scroll with a mobile device (tested only with an iPhone), touching the hamburger element won't always open the main menu. Although the hovering is active and the whole button lights up.

## Steps

I prepared a CodeSandbox: https://codesandbox.io/s/delicate-glitter-65huc?file=/src/index.js

1. Grab your Phone.
2. Go to 'https://65huc.csb.app/#'
3. Click on the hamburger (menu should open)
4. Scroll down
5. Click on the hamburger (menu does not open)
6. Repeat step 4 and 5 till you experience the issue

## Expected Behaviour

Menu should open.

## Video

https://user-images.githubusercontent.com/5459550/120302852-91cb3f80-c2ce-11eb-96e8-7c622e232430.mov

## Additional context

This issue seems related to touch events not firing reliably. Event listeners in [BaseMenu](https://github.com/NickDJM/accessible-menu/blob/c121498eea846da11060d5cbdc068efcb63e0ecd/src/_baseMenu.js#L600) are not even called. Maybe consider using another event to register toggle clicks.

In case anyone else experiences this issue, this workaround helped me:

```
controllerElement.addEventListener("click", (e) => {
    menu.menuElements.controller.toggle();
    e.preventDefault();
})
```

**Comment by NickDJM** [comment]
@calvinrbnspiess Thanks for the issue!

I followed the provided steps, but can't seem to reproduce the issue- that being said I am on Android not iOS.

I'll follow up again once I've had a chance to test in Safari. I know Safari has some issues with touch events, so maybe I'm not swapping between touch/click handling properly.

**Comment by NickDJM** [comment]
I've done a bit more testing and I can only recreate this on iOS devises (not simulated by MacOS), so at least that's a start.

**Comment by NickDJM** [comment]
I gave this a test with the latest branch I've been working on for 3.x (in this case the treeview branch) and it looks like this issue is resolved with the changes I've made to the click handler there.

I'm going to implement a similar change on the test branch and we'll see if that resolves the issue.

**Comment by NickDJM** [comment]
@calvinrbnspiess are you able to test the new dist code in the `testing-ios-toggle-issue-109` branch? I believe it should resolve the issue.

If is does, then I'll clean up the branch and get it merged into the main 2.x branch.

**Comment by calvinrbnspiess** [comment]
@NickDJM Thanks for the quick reaction!

Well, I will test the branch tomorrow when I am back at work. I hope resolving this will benefit other users as well, as this is an issue you can perhaps overlook quickly.

**Comment by calvinrbnspiess** [comment]
I tested the new code and can confirm that the issue is resolved. Good work!

Thanks

**Comment by NickDJM** [comment]
@calvinrbnspiess Just to follow up on this: v2.3.0 has this fix in it, so if you update your version to that you'll be good to go!

**Comment by calvinrbnspiess** [comment]
> @calvinrbnspiess Just to follow up on this: v2.3.0 has this fix in it, so if you update your version to that you'll be good to go!

Thank you very much :)
