### ISSUE TITLE
Bug: error during symfony encore build

### ISSUE THREAD

**Issue by FlashPanther** [NickDJM/accessible-menu#154]
## Summary
I have an error during the build (symfony encore / ibexa).

I'm sure it's not a bug but I can't find a solution so I'm posting it here.
If that's not the good place, you can close this issue!
Any help will be appreciated !

Oh, and thank you for this very interesting library !!!

## Steps to reproduce
run `yarn encore dev`

## Screenshots
![Screenshot from 2021-12-03 13-04-11](https://user-images.githubusercontent.com/1136677/144599841-0d022c7c-bbc0-4549-9f21-830953e35b49.png)

**Comment by NickDJM** [comment]
@FlashPanther This looks like it may be an issue with your build configuration. From what I can see in the error message, it looks like whatever you're using to build things doesn't support class [field declarations](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#field_declarations).

I would suggest looking into [Babel](https://babeljs.io/). That may solve your problem.

If Babel isn't an option, then you should try using the pre-compiled code provided in `accessible-menu/dist/`.
