### ISSUE TITLE
Focus hangs/placed wrongly when hovering over menu items with sub menus

### ISSUE THREAD

**Issue by phun-ky** [NickDJM/accessible-menu#209]
## Summary
Focus hangs/placed wrongly when hovering over menu items with sub menus

## Steps to reproduce

Use disclosure menu with sub menus

## Expected Behaviour
Focus is following pointer as expected

## Screenshots

See video
[Screencast from 28. mars 2023 kl. 09.31 +0200.webm](https://user-images.githubusercontent.com/1714029/228162434-8927f11b-add4-44dc-a183-0587c8904aaa.webm)

**Comment by NickDJM** [comment]
I believe this is because of the delay on closing the hovered menus. Once the menu closes it moves focus to the parent item.

A possible solution will be to move the focus immediately and worry about closing the menu after. I'll need to review that functionality in the source code to see what's up.

**Comment by NickDJM** [comment]
And to confirm the bug: I see the exact same behaviour on an application I am working on.

**Comment by NickDJM** [comment]
[accessible-menu-focus-hover-bug.webm](https://user-images.githubusercontent.com/6486142/228946011-ed083f81-5115-4bc1-b3d0-b346aabbb7e9.webm)

**Comment by NickDJM** [comment]
Ok this stems from setting the currentChild: specifically the `setParentChild()` function inside of it.

```js
  set currentChild(value) {
    isValidType("number", { value });

    /**
     * Update the parent menu's current child to make sure clicks
     * and other jumps don't interfere with keyboard navigation.
     *
     * @param {BaseMenu} menu - The initial menu.
     */
    function setParentChild(menu) {
      const updateEvents = ["mouse", "character"];

      if (
        updateEvents.includes(menu.currentEvent) &&
        menu.elements.parentMenu
      ) {
        let index = 0;
        let found = false;

        while (
          !found &&
          index < menu.elements.parentMenu.elements.menuItems.length
        ) {
          const menuItem = menu.elements.parentMenu.elements.menuItems[index];

          if (
            menuItem.isSubmenuItem &&
            menuItem.elements.toggle.elements.controlledMenu === menu
          ) {
            found = true;

            menu.elements.parentMenu.currentEvent = menu.currentEvent;
            menu.elements.parentMenu.currentChild = index;
          }

          index++;
        }
      }
    }

    if (value < -1) {
      this._currentChild = -1;
      setParentChild(this);
    } else if (value >= this.elements.menuItems.length) {
      this._currentChild = this.elements.menuItems.length - 1;
      setParentChild(this);
    } else if (this.focusChild !== value) {
      this._currentChild = value;
      setParentChild(this);
    }
  }
```

This was added to help prevent jumping back and forth in treeviews when you click on various menu links, however this clearly causes issues with hovering.

I'll need to think about how to solve this.

**Comment by NickDJM** [comment]
Going to begin working on this bug in early June.

**Comment by NickDJM** [comment]
I believe I have a fix for this. I'm going to do a little bit more manual testing before I officially merge it.

**Comment by NickDJM** [comment]
This will be a 4.x change, just because the testing is a lot stronger.

I don't have the set up for testing to be certain this won't break anything in 3.x
