### ISSUE TITLE
Feat: Add delay transition when menu opens.

### ISSUE THREAD

**Issue by SARCASMOOO** [NickDJM/accessible-menu#211]
## Summary
I want to add a transition delay when a menu or sub-menu is opened.

## Solution

I am currently working on adding a transition so the menu will open with a delay and ease in.
I am looking into adding this in the base menu toggle so a class can be added to cause a delayed transition of a menu or sub-menu opening.

Here is the snippet of code I am looking at to add an optional class for a delay which would be written in SCSS.

```
    // Add the open class
    if (openClass !== "") {
      this.elements.controlledMenu.dom.menu.classList.add(delayClass);

      if (typeof openClass === "string") {
        this.elements.controlledMenu.dom.menu.classList.add(openClass);
      } else {
        this.elements.controlledMenu.dom.menu.classList.add(...openClass);
      }
    }
```

## Alternatives
The alternative I found was to add a set time out in the handleHover method when preview is called.
Doing this will delay the menu to open but not include the transition. 

It may make more sense to figure out what to target in the handleHover function and add a class that will cause a delay transition before the preview is called. This is the relevant snippet for that inside of the baseMenu class.

```
_handleHover() {
...
         if (menuItem.isSubmenuItem) {
            menuItem.elements.toggle.preview();
          }
...
```

### Aditional Context

Currently, I wrote a SCSS class to add a delay but I am trying to figure out what is the correct element to select so the transition will work when a menu is opened. This does not work yet.

If I can find the correct element to select so the transition works then I can add the logic for when to add the class.

**Comment by NickDJM** [comment]
I like the idea, though it shouldn't be `delayClass` it would be more accurate to call it `transitionClass`.

Better yet, given that we might want to target different transitions based on opening/closing perhaps we could have `openingClass` and `closingClass`.

**Comment by NickDJM** [comment]
Coldfront Labs will be paying for this improvement. I'll start work on it in June.

**Comment by NickDJM** [comment]
I have hover delay working for showing the menus now. We'll need to figure out if the transition class is worth having. It might be, since then you can have nice transitions like:

```css
.hide {
  display: none;
}

.transitioning {
  display: block;
  opacity: 0;
}

.show {
  display: block;
  opacity: 1;
}
```

And then you can animate the transition between `opacity: 0;` and `opacity: 1;`.

**Comment by NickDJM** [comment]
This has been implemented and merged into 4.x
