### ISSUE TITLE
Bug: Menu cannot be closed by pressing the return key on a keyboard

### ISSUE THREAD

**Issue by rainerhillebrand** [NickDJM/accessible-menu#222]
## Summary
The disclosure menu for mobile devices allows its opening by focusing the menu button and pressing the return key on a keyboard. The menu cannot be closed by focusing the menu button again and pressing the return key.

## Steps to reproduce

1. Go to the "[Disclosure Menu Example](https://codepen.io/nickdjm/pen/LYBoOWX)" at GitHub.
2. Reduce the screen width until the mobile disclosure menu with the hamburger button is visible.
3. Focus the menu button.
4. Press the return key.
5. The menu is visible.
6. The first menu item "Mammals" is focused.
7. Focus the menu button by pressing Shift + Tab.
8. Press the return key.
9. The first item "Mammals" is focused again. The menu is still visible.

## Expected Behaviour
I would expect that the result of step 8 would be the hidden menu. This would be the same result like after clicking the menu button with the mouse.

**Comment by NickDJM** [comment]
@rainerhillebrand that most definitely sounds like a bug! I'll do some testing to confirm.

**Comment by NickDJM** [comment]
Just to add some more information to this issue: _Technically_ the menu controllers aren't part of the spec in the [APG](https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/examples/disclosure-navigation/), however I just assume the controllers acts like any other toggle.

In the APG's example (and in the demo menu I have) regular toggles most definitely "toggle" the controlled menu open and closed, so this is 100% a bug.

A fix should be pretty straight forward so I'll look into this in the next few days.

**Comment by NickDJM** [comment]
This is now fixed in 4.x

I'll backport this to 3.x because it should function that way.

**Comment by NickDJM** [comment]
3.x has the change now. It'll be in the next release.

**Comment by rainerhillebrand** [comment]
Dear @NickDJM,

Thanks a lot!

Best regards,

Rainer

**Comment by NickDJM** [comment]
This has been released in v3.0.6 and v4.0.0-beta.3
