### ISSUE TITLE
Bug: Menu toggled on right-click as well

### ISSUE THREAD

**Issue by nileshbhagwat** [NickDJM/accessible-menu#355]
**Issue:** Menu toggled on right-click as well

**Description:**
Currently, the menu is being toggled on both left and right mouse clicks. This is happening due to the use of `pointerup` and `pointerdown` events. These events listen to all mouse buttons (including the right-click) and are causing the menu to toggle unexpectedly.

**Reference:**  
https://github.com/NickDJM/accessible-menu/blob/4.x/src/_baseMenu.js#L1432-L1452

https://codepen.io/nickdjm/pen/wvZvXvP
![image](https://github.com/user-attachments/assets/702b3843-b40f-4a96-baea-88c31160af94)

**Steps to Reproduce:**
1. Open the menu.
2. Observe the menu toggling on right-click.

**Possible Solution:**
1. Use `click` event instead of `pointerup`.
2. **Recommended:** Block the right-click within the `toggleToggle` function to avoid regressions:
    ```javascript
    if (event.button === 2) {
        // do not toggle
    } else {
        // existing code to toggle menu
    }
    ```
    https://stackoverflow.com/questions/21610592/pointer-events-method-of-checking-left-or-right-click

**Expected Behaviour:**
- The menu should only toggle on a left-click (button 0).
- Right-click (button 2) should not trigger any toggle behavior.

**Comment by vinayakpatilcsod** [comment]
@NickDJM Can you please review this? If you approve the change, we will create a PR.

**Comment by NickDJM** [comment]
We can shortcut it to just

```js
if (event.button === 2) {
  return;
}
```

Otherwise, this makes sense to me. Will need to make sure this works on mobile, and also add some tests for right-click vs. left-click.

**Comment by NickDJM** [comment]
Actually, we should probably use button `0`, so `if (event.button !== 0)`.

**Comment by vinayakpatilcsod** [comment]
okay, thank you @NickDJM! @nileshbhagwat Let's create a PR for the same.

**Comment by NickDJM** [comment]
The related PR has been merged. Thanks very much!

I'd like to get #354 resolved and then I'll make a new release with this in it.

**Comment by vinayakpatilcsod** [comment]
@NickDJM Could we consider releasing this fix? It's currently blocking our production release.

**Comment by NickDJM** [comment]
@vinayakpatilcsod I will need some time to work on #354 before I make a release. If you're able to help out with that issue, that would be the fastest way to get a release out.

**Comment by NickDJM** [comment]
This has been release with v4.2.0
