### ISSUE TITLE
Feat: Support multiple and empty open/close classes

### ISSUE THREAD

**Issue by NickDJM** [NickDJM/accessible-menu#72]
It would be super handy to support both multiple and no classes in the openClass/closeClass props.

This would allow for more customization (especially with utility libraries like TailwindCSS).

**Comment by NickDJM** [comment]
Features are merged in. Just want to make sure they work in all browsers before a release is made.

**Comment by NickDJM** [comment]
This doesn't work in IE at all- Class lists are barely supported.

Need to refactor the current classList manipulation to work with IE.

**Comment by guettli** [comment]
Is IE support needed?

**Comment by NickDJM** [comment]
@guettli I have clients that have to support IE11, so this project needs to as well.

**Comment by NickDJM** [comment]
This now works in IE. Going to run a release now that this is closed.
