### ISSUE TITLE
Replace pseudocode example in README with real HTML

### ISSUE THREAD

**Issue by guettli** [NickDJM/accessible-menu#75]
Hi,

thank you for this library!

Why do you use this in the README?

```
<menu>
  <menu-item><a>...</a></menu-item>
```
In the examples you use the `<nav>` and `<ul>` (which make more sense to me).

**Comment by NickDJM** [comment]
The README structure example was made when the project was more conceptual. I do agree its a little confusing to have pseudocode rather than a basic HTML example.

A rewrite there definitely makes sense!

**Comment by guettli** [comment]
Thank you
