### ISSUE TITLE
Why is your solution better then bootstrap4 navbar?

### ISSUE THREAD

**Issue by guettli** [NickDJM/accessible-menu#77]
Why is your solution better than [bootstrap4 navbar](https://getbootstrap.com/docs/4.0/components/navbar/)?

**Comment by NickDJM** [comment]
@guettli "Better" is definitely a subjective term.

I will say that the Bootstrap 4 navbar does not come with proper keybindings by default (as far as [aria guidelines](https://www.w3.org/TR/wai-aria-practices-1.2/) are concerned). Accessible menu just makes it easy for you to add those keybindings (and aria attributes) to your styled menus.

The main goal of this project was to make accessible navigation super quick and super easy to implement, not necessarily to be "better" than any other project.

**Comment by guettli** [comment]
If it is quicker and easier, then it is better. Thank you for your answers.

I know good developers prefer coding to advertising, but I think you could state the benefits of your approach in the README.
