### ISSUE TITLE
Feat: less attributes in html, simpler examples

### ISSUE THREAD

**Issue by guettli** [NickDJM/accessible-menu#78]
I am looking at this html:

https://github.com/NickDJM/accessible-menu/blob/dev/test/Menubar.html

it contains a `<li class="menu-item"...` very often.

Wouldn't it be nice to have it simpler?

If you compare this to this: https://jqueryui.com/menu/

The jquery-ui html code is very clean: Just `<ul>` and `<li>`.

It would help new users, and make the library more attractive if the basic usage works like in the jquery-ui example: without css classes.

**Comment by NickDJM** [comment]
The classes come from pre-2.0.0 where this was mostly based on a BS4 menu structure. With the change to 2.0.0 and focusing more on being a little more universal, the classes weren't needed as much.

I'll keep this in mind when I get around to writing some automated tests, but as far as "examples" go, the test files shouldn't be taken as pure examples.

**Comment by NickDJM** [comment]
Basic test files have been simplified and 99% of classes have been removed. This essentially resolves this issue regardless of the above mentioned automation part.

Closing.
