### ISSUE TITLE
Feat: Emit event when switching between visible and hidden state

### ISSUE THREAD

**Issue by FlyKasual** [NickDJM/accessible-menu#90]
Hi

First off: Huge thank you for this awesome package! I love how much it adds to our websites in terms of accessibility.

One thing I would like to do is bind the state of other elements to the state of a menu. For example: When a Menubar shows, I'd like to also show a backdrop obscuring everything but the menu to reduce distractions from the rest of the website; when the MenuBar hides again, I'd like to also hide the backdrop. I believe, one way to achieve such a thing would be to let MenuToggle extend EvenTarget and have it emit an Event in e.g. the open, close or toggle methods. This way, one could do something like this:
```
const myMenu = AccessibleMenu.Menubar({
  // Options
})
myMenu.dom.controller.addEventListener('stateChange', evt => {
  // do something depending on the menu's state, e.g. show or hide backdrop
})
```

**Comment by NickDJM** [comment]
@FlyKasual happy to hear you're enjoying accessible-menu, and thanks for the issue!

I definitely like the idea of having a custom event that is emitted when a menu opens/closes. I think it would be pretty straight forward to add.

I'll see about getting a branch up with a basic implementation to see how it goes.

**Comment by NickDJM** [comment]
@FlyKasual You can check out the branch in the above mentioned PR and see if that works for you. If it does, I don't see any issue with merging it into dev.

I added the toggle itself to the `event.detail` prop in case you need access to it inside the event handler.

**Comment by FlyKasual** [comment]
Hi Nick

Thanks for the quick response! I'll check out the PR and come back to you ASAP

**Comment by FlyKasual** [comment]
Hi again!

This seems to work like an absolute charm in my use-case. Thank you very much for implementing this so quickly! <3 I love that the event actually bubbles.
I see no reason why this should not be merged into dev.

**Comment by NickDJM** [comment]
@FlyKasual The feature has been merged into dev. 

I don't have an exact time for when I'm going to make the next release (there's a couple of things I need to try first), but for now the dev branch has what you're looking for.

**Comment by NickDJM** [comment]
This is now release with v2.2.0
