### ISSUE TITLE
Bug: Circular dependencies

### ISSUE THREAD

**Issue by vf-telwing** [NickDJM/accessible-menu#95]
I noticed you recently merged browser module support into `next` to help resolve issues with circular dependencies, but they are still present. There are loops between `BaseMenu`/`BaseMenuToggle` and `validate.js` because of the `isMenu()` and `isMenuToggle()` implementations.

One solution could be using `Symbol` to act as the unique identifier for a class. I quickly tested this idea by creating a file containing the symbols:
```
// _baseTypes.js
export const baseMenu = Symbol('BaseMenu');
export const baseMenuToggle = Symbol('BaseMenuToggle');
```

Then, adding a Symbol member to each respective class:
```
// _baseMenu.js
import { baseMenu } from "./_baseTypes.js";

class BaseMenu {
    // ...
    get [baseMenu]() {
        return true;
    }
}
```

It would then be possible to rely on the Symbol for validation rather than the class name (thus avoiding the circular import):
```
// validate.js
import { baseMenu } from "./_baseTypes.js";

function isMenu(element) {
    // ...
    if (!(element[baseMenu])) {
        // ...
    }
}
```

I realize this is probably not ideal and an extra `Symbol` polyfill would be required for IE, but I wanted to at least try and provide a solution.

**Comment by NickDJM** [comment]
@vf-telwing Hey, thanks for this!

I'm not _super_ concerned with adding one more polyfill for IE, so this solution definitely works!

**Comment by vf-telwing** [comment]
Would you accept a PR using this method? Or did you already have a different solution?

**Comment by NickDJM** [comment]
I would accept a PR for sure! Thanks
